#!/bin/bash

fetch=$1

source $fetch

echo ARCHIVE=$ARCHIVE

set +e

if [ "x" != "x$SKIP_FETCH" ]; then
	echo "Skip fetching $ARCHIVE"
else
	echo "Fetch $ARCHIVE from $URL "
	export ARCHIVE
	export URL
	export BUILD
	bash $BUILD_TOOL_PATH/fetch_archive
fi

set -e

bash $BUILD_TOOL_PATH/build_archive	
