#!/bin/bash

set -e

if [ "x" == "x$MONO_PREFIX" ]; then
	echo "MONO_PREFIX is not set"
	exit 1
fi

echo "create $MONO_PREFIX"
sudo mkdir -p $MONO_PREFIX

source mono_env $MONO_PREFIX

$BUILD_TOOL_PATH/build_sources

