#!/bin/bash

set -e

if [ "x" == "x$MONO_PREFIX" ]; then
	echo "MONO_PREFIX is not set"
	exit 1
fi

source mono_env $MONO_PREFIX

export BUILD_TOOL_PATH=$HOME
export SOURCE_DIR="$HOME/sources"
export ARCHIVE_DIR="$HOME/archives"

$BUILD_TOOL_PATH/build_sources

