#!/bin/bash

set -e

if [ "x" == "x$ARCHIVE_DIR" ] 
then
   echo "run build_mono first"
   exit
fi

echo "ARCHIVE_DIR=$ARCHIVE_DIR"
echo "SOURCE_DIR=$SOURCE_DIR"

DIRS=$BUILD_GROUP

if [ "x" == "x$BUILD_GROUP" ]
then
  DIRS=$ARCHIVE_DIR/*.d
fi

for grp in $DIRS
do
  echo +++++++++++++++++++++++++++++++++++
  gname=`basename $grp`
  echo "starting group : $gname"
  echo -----------------------------------


  for fetch in $grp/*.get
  do
     echo $fetch
     bash $BUILD_TOOL_PATH/build_one $fetch
  done
done

