#!/bin/bash

set -e

if [ "x" == "x$ARCHIVE_DIR" ] 
then
   echo "run build_mono first"
   exit
fi

echo "ARCHIVE_DIR=$ARCHIVE_DIR"
echo "SOURCE_DIR=$SOURCE_DIR"

for fetch in $ARCHIVE_DIR/*.get
do
	bash $BUILD_TOOL_PATH/build_one $fetch
done

