#!/bin/bash

fetch=$1

source $fetch

echo ARCHIVE=$ARCHIVE

GRP=`dirname $fetch`
BUILD=$ARCHIVE_DIR/../$GRP/$BUILD
export BUILD
export ARCHIVE
export URL

echo "GRP=$GRP"
echo "BUILD=$BUILD"

set +e

if [ "x" != "x$NOFETCH" ]; then
	echo "Skip fetching $ARCHIVE"
else
	echo "Fetch $ARCHIVE from $URL "
	bash $BUILD_TOOL_PATH/fetch_archive
fi

set -e

bash $BUILD_TOOL_PATH/build_archive	
