#!/bin/bash

set -e

function pmono_deb {

 PNAME=$1
 PVERS=$2
 PDEPS=$3
 PMAINT="$4" ## this doesnt work..
 PURL=$5
 PREFIX=$MONO_PREFIX
 OUTDIR=$ARCHIVE_DIR
 EXCLUDE=$GLOBAL_EXCLUDE

 ARCH=`dpkg-architecture -qDEB_HOST_ARCH`

 sudo rm -rf ~/tmp/pmono_pkg/
 mkdir -p ~/tmp/pmono_pkg/

 BEFORESIZE=`du -s -m $MONO_PREFIX|cut -d \/ -f 1`

 perl ~/dir_changes $MONO_PREFIX ~/tmp/pmono_pkg/data.tar sudo -E make install
 perl ~/dir_changes /usr/local ~/tmp/pmono_pkg/data.tar sudo -E make install


 AFTERSIZE=`du -s -m $MONO_PREFIX|cut -d \/ -f 1`

 SIZE=$(($AFTERSIZE-$BEFORESIZE))

 pushd ~/tmp/pmono_pkg

 echo "Package: $PNAME" > control
 echo "Version: $PVERS-$GLOBAL_RELEASE_NUMBER" >> control
 echo "Priority: optional" >> control
 echo "Architecture: $ARCH" >> control
 echo "Depends: $PDEPS" >> control
 echo "Installed-Size: $SIZE" >> control
 echo -n "Maintainer: " >> control
 echo $GLOBAL_MAINTAINER >> control
 echo "Description: The $PNAME package provides part of a parallel mono" >> control
 echo " environment that won't get in the way of your system installed mono." >> control


 mkdir -p debian/DEBIAN
 mv control debian/DEBIAN/.
 
 pushd debian
 sudo tar -psxf ../data.tar
 popd

 find ./debian -type d | sudo xargs chmod 755

 dpkg-deb --build debian ~/archives/

 popd

}

pmono_deb $@
