#!/bin/bash
set -e

mkdir -p repo
cd repo

rm -rf pmono
mkdir -p pmono

set +e
find ../archives/ -name '*.deb' -type f -exec mv '{}' pmono/. \;
set -e

scp -r pmono bredroll@void.printf.net:public_html/pmono/.
ssh bredroll@void.printf.net "cd public_html/pmono; dpkg-scanpackages -m . /dev/null |gzip -9c > Packages.gz"
